version: '3.9'
services:
  frontend:
    command: 'npm run build'
    build:
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
