name: Netlify Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build check since netlify doesnt notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install node dependencies
        run: npm install
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: install python dependencies
        run: |
          python3 -m pip install --upgrade pip==22.2.2
          pip3 install -r requirements.txt
      - name: Update notebooks
        run: |
          nbdoc_update
          nbdoc_build
