name: georgerowlands.ch Actions

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:
  link-network:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: octocat/docusaurus-link-action@v0.1
        with:
          who-to-greet: 'Me Mario'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
